development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
<<<<<<< HEAD
  channel_prefix: sample_app_production
=======
<<<<<<< HEAD
  channel_prefix: sample_app_production
=======
  channel_prefix: toy_app_production
>>>>>>> origin/master
>>>>>>> origin/master
