# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ad1987d71a0f61c9186f62882da944b9728aa091c50ef84f1568a32e38e69eb9a0b6e9686af2458e24ab815982208fc136bc499957f6d915fd216ee79d98368

test:
  secret_key_base: e719e2e735188ad406f56fba6654ee9772d729510d150d8d4b9938c80d2bc124ea2d4b184afb4d29acf653f2e11e8e896f1709c3b149cc488888a937fe10c359

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
